### ISSUE TITLE
TypeError in 6.3.1 when running from command line

### ISSUE THREAD

**Issue by mynameiscfed** [splunk/eventgen#106]
I am trying to run splunk_eventgen from the cli and in 6.3.1 I receive the following error:

root@a4f5754704bb:~# splunk_eventgen -v generate eventgen.conf 
2018-11-20 00:44:43 eventgen        INFO     MainProcess Logging Setup Complete.
Traceback (most recent call last):
  File "/usr/local/bin/splunk_eventgen", line 9, in <module>
    load_entry_point('splunk-eventgen==6.3.1', 'console_scripts', 'splunk_eventgen')()
  File "/usr/local/lib/python2.7/dist-packages/splunk_eventgen-6.3.1-py2.7.egg/splunk_eventgen/__main__.py", line 293, in main
    eventgen = eventgen_core.EventGenerator(args=args)
  File "/usr/local/lib/python2.7/dist-packages/splunk_eventgen-6.3.1-py2.7.egg/splunk_eventgen/eventgen_core.py", line 74, in __init__
    self._load_config(self.args.configfile, args=args)
  File "/usr/local/lib/python2.7/dist-packages/splunk_eventgen-6.3.1-py2.7.egg/splunk_eventgen/eventgen_core.py", line 111, in _load_config
    self.config = Config(configfile, **new_args)
TypeError: __init__() got an unexpected keyword argument 'verbosity'

With tag 6.3.0 it appears to run fine.

**Comment by arctan5x** [comment]
Hi. We just released 6.3.2 with the patch. Please try it out and let us know.

**Comment by mynameiscfed** [comment]
It works. Thanks for the quick release and follow up.
