### ISSUE TITLE
EventGen 6.3.2 not working with host.token fields in eventgen.conf files

### ISSUE THREAD

**Issue by gjanders** [splunk/eventgen#112]
Downloaded eventgen 6.3.2 from SplunkBase, and it failed to work with the [SPL examples app](https://splunkbase.splunk.com/app/3456/)

The error was:
2018-11-22 04:01:35,018 INFO [Eventgen] Config made Splunk Embedded
2018-11-22 04:01:35,781 ERROR [Eventgen] invalid literal for int() with base 10: 'o'
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SA-Eventgen/bin/modinput_eventgen.py", line 120, in run
    eventgen.config.parse()
  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/eventgenconfig.py", line 316, in parse
    if 'token' in key and int(key[6]) > last_token_number:
ValueError: invalid literal for int() with base 10: 'o'

Eventually I found that just before the error I could log:
2018-11-22 04:01:35 eventgen        ERROR    MainProcess host.token

So host.token was failing to parse, switched to EventGen 6.2.1 from SplunkBase and the issue goes away!

**Comment by jmeixensperger** [comment]
Including this fix in the next release.

**Comment by arctan5x** [comment]
Fix will be shippted in 6.3.3.

Closing this issue. Feel free to reopen if you see it in the new release.
