### ISSUE TITLE
[BUG] Eventgen crashes when backfill < interval 

### ISSUE THREAD

**Issue by li-wu** [splunk/eventgen#158]
**Describe the bug**
When setting `backfill = -5s` with default interval which is 60s in `replay` mode will make eventgen replay the sample once and crash.

**To Reproduce**
eventgen.conf:
```
[replay]
backfill = -5s
sampletype = raw
outputMode = stdout
mode = replay
end = 2
token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}
token.0.replacementType = replaytimestamp
token.0.replacement = %Y-%m-%d %H:%M:%S
token.1.token = @@integer
token.1.replacementType = random
token.1.replacement = integer[0:10]
```
`replay` sample:
```
2014-01-04 20:00:00 WINDBAG Event 1 of 12 randint @@integer
2014-01-04 20:00:01 WINDBAG Event 2 of 12 randint @@integer
2014-01-04 20:00:02 WINDBAG Event 3 of 12 randint @@integer
2014-01-04 20:00:03 WINDBAG Event 4 of 12 randint @@integer
2014-01-04 20:00:03 WINDBAG Event 5 of 12 randint @@integer
2014-01-04 20:00:04 WINDBAG Event 6 of 12 randint @@integer
2014-01-04 20:00:05 WINDBAG Event 7 of 12 randint @@integer
2014-01-04 20:00:06 WINDBAG Event 8 of 12 randint @@integer
2014-01-04 20:00:08 WINDBAG Event 9 of 12 randint @@integer
2014-01-04 20:00:20 WINDBAG Event 10 of 12 randint @@integer
2014-01-04 20:00:21 WINDBAG Event 11 of 12 randint @@integer
2014-01-04 20:00:21 WINDBAG Event 12 of 12 randint @@integer
```

**Expected behavior**
Expected the `backfill` setting is ignored since it is less than the interval.

**Actual behavior**
It throws an error after replay the whole sample once:
```
2019-04-15 14:00:38 eventgen        ERROR    MainProcess cannot deepcopy this match object
Traceback (most recent call last):
  File "splunk_eventgen/lib/eventgentimer.py", line 184, in real_run
    tokens = copy.deepcopy(self.sample.tokens)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this match object
```

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: 2.7
 - OS: MacOS 10.13.6
 - Virtual Env is used: Yes
 - Eventgen Version 6.3.4

**Comment by arctan5x** [comment]
also backfill isn't getting counted towards "end", so fixing that in this issue as well.

**Comment by arctan5x** [comment]
@li-wu I made a PR with a fix. Would you verify that the fix passes your tests regarding this case? 
https://github.com/splunk/eventgen/pull/162
