### ISSUE TITLE
[BUG] default jinja template dir is not correctly resolved when sampleDir is set in conf file

### ISSUE THREAD

**Issue by GordonWang** [splunk/eventgen#167]
**Describe the bug**
As the title. when setting sampleDir in sample stanza, the jinja template dir is not resolved correctly.

**To Reproduce**
1. use this conf stanza
```
[test_jinja_template_customized_dir]
end = 1
count = 1
sampleDir = tests/large/sample
generator = jinja
jinja_template_dir = tests/large/sample/templates_4_test
jinja_target_template = test_jinja_tmpl_dir.j2
jinja_variables = {"large_number":10}
earliest = -3s
latest = now
outputMode = stdout
```
2. create a sub dir in "tests/large/sample" named "templates"
3. put template files into templates dir.
4. run eventgen with the conf, error is thrown
```
2019-04-17 17:57:12 eventgen        ERROR    MainProcess Error loading sample file for sample 'test_jinja_template_simple'
2019-04-17 17:57:12 eventgen        ERROR    MainProcess test_jinja_tmpl_simple.j2
Traceback (most recent call last):
  File "/Users/gwang/.conda/envs/eventgen/lib/python2.7/site-packages/splunk_eventgen/lib/plugins/generator/jinja.py", line 218, in gen
    jinja_loaded_template = jinja_env.get_template(str(self._sample.jinja_target_template))
  File "/Users/gwang/.conda/envs/eventgen/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/gwang/.conda/envs/eventgen/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/gwang/.conda/envs/eventgen/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/gwang/.conda/envs/eventgen/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: test_jinja_tmpl_simple.j2
```

**Expected behavior**
default templates dir should be "tests/large/sample/templates"

**Actual behavior**
template not found

**Screenshots**
N/A

**Sample files and eventgen.conf file**
See describe section

**Do you run eventgen with SA-eventgen?**
No

** using eventgen with pip module mode (please complete the following information):**
 - python version: 2.7
 - OS: macos
 - Virtual Env is used: yes
 - Eventgen Version 6.3.4

**Additional context**

**Comment by jmeixensperger** [comment]
Do we also want to search in "<working_dir>/sample/templates"? Or just "<sampleDir>/templates"?
