### ISSUE TITLE
[BUG] Eventgen urllib3 1.24.2 version missing orderedDict

### ISSUE THREAD

**Issue by arctan5x** [splunk/eventgen#198]
**Describe the bug**
orderedDict module is missing from urllib3 1.24.2

**To Reproduce**
1. Install latest Eventgen as a pip module (6.3.5)
2. run "splunk_eventgen --version"

**Expected behavior**

**Actual behavior**
A clear and concise description of what happens after doing the reproduce steps.

**Screenshots**
`/usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/tonyl/Downloads/eventgen-6.3.5/splunk_eventgen/__main__.py", line 15, in <module>
    import requests
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/local/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/local/lib/python2.7/site-packages/requests/compat.py", line 48, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict`

**Sample files and eventgen.conf file**
N/A

**Do you run eventgen with SA-eventgen?**
No

**If you are using SA-Eventgen with Splunk (please complete the following information):**
 - OS: [e.g. Windows/Mac OS 10.14]
 - Eventgen Version [e.g. 22]

 - Splunk Version[e.g. 7.1.3]
 - What other apps you have installed in Splunk etc/apps?

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: [e.g. 2.6]
 - OS: [e.g. Windows10]
 - Virtual Env is used: Yes/No
 - Eventgen Version [e.g. 6.3.2]

**Additional context**

**Comment by li-wu** [comment]
@arctan5x I tried the latest 6.3.5 `tar.gz` as well as the latest `develop` branch build in my local virtualenv and I can not reproduce the issue.

**Comment by GordonWang** [comment]
I can not reproduce this on latest dev branch either.
