### ISSUE TITLE
[BUG] fileName for file output receives an incorrect value

### ISSUE THREAD

**Issue by arctan5x** [splunk/eventgen#228]
**Describe the bug**

Seems like the file output grabs a wrong fileName. fileName becomes a sample file name instead of the actual output fileName. When fileName is actually set in a sample stanza, it works fine. If we try to pass fileName through global, it doesn't work.

`2019-05-30 11:28:35 eventgen        ERROR    MainProcess Exception <type 'exceptions.IOError'> happened.
Traceback (most recent call last):
  File "/Users/tonyl/Desktop/eventgen/splunk_eventgen/lib/generatorplugin.py", line 64, in build_events
    self._out.flush(endOfInterval=True)
  File "/Users/tonyl/Desktop/eventgen/splunk_eventgen/lib/eventgenoutput.py", line 113, in flush
    outputer = self.outputPlugin(self._sample, self.output_counter)
  File "/Users/tonyl/Desktop/eventgen/splunk_eventgen/lib/plugins/output/file.py", line 32, in __init__
    self._fileHandle = open(self._file, 'a')`

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what happens after doing the reproduce steps.

**Screenshots**

**Sample files and eventgen.conf file**
Please attach your sample files and eventgen conf file

**Do you run eventgen with SA-eventgen?**
Yes/No(No means you run eventgen with pip module mode)

**If you are using SA-Eventgen with Splunk (please complete the following information):**
 - OS: [e.g. Windows/Mac OS 10.14]
 - Eventgen Version [e.g. 22]
 - Splunk Version[e.g. 7.1.3]
 - What other apps you have installed in Splunk etc/apps?

**If you are using eventgen with pip module mode (please complete the following information):**
eg latest develop

**Additional context**

**Comment by arctan5x** [comment]
PR Pending.
