### ISSUE TITLE
EVENTGEN DON´T GENERATE NOTHING

### ISSUE THREAD

**Issue by hbasilio** [splunk/eventgen#27]
Hello friends.

I do everything indicates the video Get Started with the Eventgen!(http://youtu.be/9S-ZeGEfRKg?hd=1) but it does not work eventgen.

Install both Windows 7 and Linux Fedora 21 and nothing does not generate any data.

In splunk courses the teachers say you can use this application but I can not do that functions

Help Thanks

Horacio

**Comment by dmaislin** [comment]
Probably because your app is not global and eventgen can't see the eventgen.conf file in your app.  Change your app permissions.

**Comment by hbasilio** [comment]
Thanks for answering.
I tell you that the app is configure "Global".

I could see is that it has some degree of inconsistency with python 2.7
While not load module HASHLIB

I step error:

/opt/Splunk/splunk/etc/apps/eventgen
[splunk@SRVLAB001 eventgen]$ python bin/eventgen.py README/eventgen.conf.tutorial2
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
Traceback (most recent call last):
  File "bin/eventgen.py", line 16, in <module>
    from eventgenconfig import Config
  File "/opt/Splunk/splunk/etc/apps/eventgen/lib/eventgenconfig.py", line 12, in <module>
    from eventgensamples import Sample, Token
  File "/opt/Splunk/splunk/etc/apps/eventgen/lib/eventgensamples.py", line 12, in <module>
    from eventgenoutput import Output
  File "/opt/Splunk/splunk/etc/apps/eventgen/lib/eventgenoutput.py", line 5, in <module>
    import httplib, httplib2
  File "/opt/Splunk/splunk/lib/python2.7/site-packages/httplib2/__init__.py", line 49, in <module>
    import sha
  File "/opt/Splunk/splunk/lib/python2.7/sha.py", line 10, in <module>
    from hashlib import sha1 as sha
ImportError: cannot import name sha1
[splunk@SRVLAB001 eventgen]$

AND

[splunk@SRVLAB001 eventgen]$ python -c "import hashlib"
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
[splunk@SRVLAB001 eventgen]$


Any suggestions?

Horacio

**Comment by hbasilio** [comment]
Thanks for answering.I tell you that the app is configure "Global".
I could see is that it has some degree of inconsistency with python 2.7While not load module HASHLIB
I step error:
/opt/Splunk/splunk/etc/apps/eventgen[splunk@SRVLAB001 eventgen]$ python bin/eventgen.py README/eventgen.conf.tutorial2ERROR:root:code for hash md5 was not found.Traceback (most recent call last):  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 139, in <module>    globals()[__func_name] = __get_hash(__func_name)  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor    raise ValueError('unsupported hash type ' + name)ValueError: unsupported hash type md5ERROR:root:code for hash sha1 was not found.Traceback (most recent call last):  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 139, in <module>    globals()[__func_name] = __get_hash(__func_name)  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor    raise ValueError('unsupported hash type ' + name)ValueError: unsupported hash type sha1Traceback (most recent call last):  File "bin/eventgen.py", line 16, in <module>    from eventgenconfig import Config  File "/opt/Splunk/splunk/etc/apps/eventgen/lib/eventgenconfig.py", line 12, in <module>    from eventgensamples import Sample, Token  File "/opt/Splunk/splunk/etc/apps/eventgen/lib/eventgensamples.py", line 12, in <module>    from eventgenoutput import Output  File "/opt/Splunk/splunk/etc/apps/eventgen/lib/eventgenoutput.py", line 5, in <module>    import httplib, httplib2  File "/opt/Splunk/splunk/lib/python2.7/site-packages/httplib2/__init__.py", line 49, in <module>    import sha  File "/opt/Splunk/splunk/lib/python2.7/sha.py", line 10, in <module>    from hashlib import sha1 as shaImportError: cannot import name sha1[splunk@SRVLAB001 eventgen]$
AND
[splunk@SRVLAB001 eventgen]$ python -c "import hashlib"ERROR:root:code for hash md5 was not found.Traceback (most recent call last):  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 139, in <module>    globals()[__func_name] = __get_hash(__func_name)  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor    raise ValueError('unsupported hash type ' + name)ValueError: unsupported hash type md5ERROR:root:code for hash sha1 was not found.Traceback (most recent call last):  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 139, in <module>    globals()[__func_name] = __get_hash(__func_name)  File "/opt/Splunk/splunk/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor    raise ValueError('unsupported hash type ' + name)ValueError: unsupported hash type sha1[splunk@SRVLAB001 eventgen]$

Any suggestions?
Thank
Horacio 



     El Viernes, 29 de mayo, 2015 8:49:31, dmaislin <notifications@github.com> escribió:
   

 Probably because your app is not global and eventgen can't see the eventgen.conf file in your app. Change your app permissions.—

**Comment by dmaislin** [comment]
That is odd.  I have same Python 2.7.8 and all works perfectly fine.

dmaislin-mbp:eventgen dmaislin$ python -V
Python 2.7.8


dmaislin-mbp:eventgen dmaislin$ python bin/eventgen.py README/eventgen.conf.tutorial2
2015-05-29 08:02:42,466 INFO Starting eventgen
2015-05-29 08:02:47,466 INFO Retrieving eventgen configurations with ConfigParser()
2015-05-29 08:02:47,470 DEBUG ConfDict returned {'default': {'eai:acl': {'app': 'eventgen'}},
 'global': {'breaker': '[^\\r\\n\\s]+',
            'count': '0',
            'debug': 'true',
            'delay': '0',
            'disabled': 'false',
            'eai:acl': {'app': 'eventgen'},
            'earliest': 'now',
            'fileBackupFiles': '5',
            'fileMaxBytes': '10485760',
            'host': '127.0.0.1',
            'index': 'main',
            'interval': '60',
            'latest': 'now',
            'mode': 'sample',
            'outputMode': 'spool',
            'randomizeEvents': 'false',
            'sampletype': 'raw',
            'source': 'eventgen',
            'sourcetype': 'eventgen',
            'splunkMethod': 'https',
            'splunkPort': '8089',
            'spoolDir': '$SPLUNK_HOME/var/spool/splunk',
            'spoolFile': '<SAMPLE>',
            'timeMultiple': '1'},
 'sample.tutorial2': {'count': '20',
                      'dayOfWeekRate': '{ "0": 0.7, "1": 0.7, "2": 0.7, "3": 0.5, "4": 0.5, "5": 1.0, "6": 1.0 }',
                      'eai:acl': {'app': 'eventgen'},
                      'earliest': '-15s',
                      'fileName': '/tmp/ciscosample.log',
                      'hourOfDayRate': '{ "0": 0.8, "1": 1.0, "2": 0.9, "3": 0.7, "4": 0.5, "5": 0.4, "6": 0.4, "7": 0.4, "8": 0.4, "9": 0.4, "10": 0.4, "11": 0.4, "12": 0.4, "13": 0.4, "14": 0.4, "15": 0.4, "16": 0.4, "17": 0.4, "18": 0.4, "19": 0.4, "20": 0.4, "21": 0.4, "22": 0.5, "23": 0.6 }',
                      'interval': '15',
                      'latest': 'now',
                      'outputMode': 'file',
                      'randomizeCount': '0.2',
                      'randomizeEvents': 'true',
                      'token.0.replacement': '%b %d %H:%M:%S',
                      'token.0.replacementType': 'timestamp',
                      'token.0.token': '\\w{3}\\s+\\d{1,2}\\s+\\d{2}:\\d{2}:\\d{2}'}}
2015-05-29 08:02:47,470 DEBUG Validating setting for 'timeMultiple' with value '1' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'spoolFile' with value '<SAMPLE>' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'randomizeEvents' with value 'false' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'index' with value 'main' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'spoolDir' with value '$SPLUNK_HOME/var/spool/splunk' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'debug' with value 'true' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'interval' with value '60' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'splunkMethod' with value 'https' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'splunkPort' with value '8089' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'mode' with value 'sample' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'breaker' with value '[^\r\n\s]+' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'fileMaxBytes' with value '10485760' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'source' with value 'eventgen' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'delay' with value '0' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'outputMode' with value 'spool' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'earliest' with value 'now' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'eai:acl' with value '{'app': 'eventgen'}' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'sampletype' with value 'raw' in stanza 'global'
2015-05-29 08:02:47,470 DEBUG Validating setting for 'latest' with value 'now' in stanza 'global'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'disabled' with value 'false' in stanza 'global'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'fileBackupFiles' with value '5' in stanza 'global'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'count' with value '0' in stanza 'global'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'host' with value '127.0.0.1' in stanza 'global'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'sourcetype' with value 'eventgen' in stanza 'global'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'randomizeCount' with value '0.2' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'fileName' with value '/tmp/ciscosample.log' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'hourOfDayRate' with value '{ "0": 0.8, "1": 1.0, "2": 0.9, "3": 0.7, "4": 0.5, "5": 0.4, "6": 0.4, "7": 0.4, "8": 0.4, "9": 0.4, "10": 0.4, "11": 0.4, "12": 0.4, "13": 0.4, "14": 0.4, "15": 0.4, "16": 0.4, "17": 0.4, "18": 0.4, "19": 0.4, "20": 0.4, "21": 0.4, "22": 0.5, "23": 0.6 }' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'outputMode' with value 'file' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'token.0.token' with value '\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,471 INFO Getting time (timezone 1 day, 0:00:00)
2015-05-29 08:02:47,471 DEBUG Validating setting for 'earliest' with value '-15s' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'interval' with value '15' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'eai:acl' with value '{'app': 'eventgen'}' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,471 DEBUG Validating setting for 'token.0.replacementType' with value 'timestamp' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,472 DEBUG Validating setting for 'latest' with value 'now' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,472 DEBUG Validating setting for 'token.0.replacement' with value '%b %d %H:%M:%S' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,472 DEBUG Validating setting for 'randomizeEvents' with value 'true' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,472 DEBUG Validating setting for 'count' with value '20' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,472 DEBUG Validating setting for 'dayOfWeekRate' with value '{ "0": 0.7, "1": 0.7, "2": 0.7, "3": 0.5, "4": 0.5, "5": 1.0, "6": 1.0 }' in stanza 'sample.tutorial2'
2015-05-29 08:02:47,472 ERROR Sample 'sample.tutorial2' in config but no matching files
2015-05-29 08:02:47,473 DEBUG Finished parsing.  Config str:
Config:{'_confDict': None,
 '_firsttime': False,
 '_isOwnApp': True,
 'breaker': '[^\\r\\n\\s]+',
 'count': 0,
 'debug': 'true',
 'delay': 0.0,
 'disabled': False,
 'eai:acl': {'app': 'eventgen'},
 'earliest': 'now',
 'fileBackupFiles': 5,
 'fileMaxBytes': 10485760,
 'grandparentdir': '/splunk/demo/etc/apps/eventgen',
 'greatgrandparentdir': '/splunk/demo/etc/apps',
 'host': '127.0.0.1',
 'index': 'main',
 'interval': 60,
 'latest': 'now',
 'mode': 'sample',
 'outputMode': 'spool',
 'randomizeEvents': False,
 'sampleDir': '/splunk/demo/etc/apps/eventgen/samples',
 'sampletype': 'raw',
 'source': 'eventgen',
 'sourcetype': 'eventgen',
 'splunkMethod': 'https',
 'splunkPort': 8089,
 'spoolDir': '$SPLUNK_HOME/var/spool/splunk',
 'spoolFile': '<SAMPLE>',
 'timeMultiple': 1.0}
Samples:
[]
2015-05-29 08:02:47,473 INFO Starting timers
^C

Caught kill, exiting...

**Comment by malcojosh** [comment]
This happens if you call python directly instead of:

`%SPLUNK_HOME%\bin\splunk cmd python something.py`

**Comment by lephino** [comment]
The default inside of splunk is to use the modinput.  Outside of splunk you're now able to fully run in a native python instance.  Just make sure to install httplib2 and requests with pip.
