### ISSUE TITLE
splunkstream isnot working with default splunk installation in windows x64

### ISSUE THREAD

**Issue by donixa** [splunk/eventgen#61]
splunkstream is not working with default splunk installation in windows x64.

Tried:
installing different version of python, 32 or 64,
also tried modified of Tuturial3

Tried:
**server.conf**
[sslConfig]
requireClientCert = false

**inputs.conf**
[SSL]
requireClientCert = false

Tried: Tutorial4, and is not working, will output like below.

**C:\Program Files\Splunk\etc\apps\SA-Eventgen>python bin\eventgen.py readme\eventgen.conf.tutorial4**
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Program Files\Splunk\etc\apps\SA-Eventgen\lib\outputworker.py", line 40, in run
    self.worker.run()
  File "C:\Program Files\Splunk\etc\apps\SA-Eventgen\lib\outputworker.py", line 74, in run
    self.real_run()
  File "C:\Program Files\Splunk\etc\apps\SA-Eventgen\lib\outputworker.py", line 96, in real_run
    plugin.flush(deque(queue[:]))
  File "C:\Program Files\Splunk\etc\apps\SA-Eventgen\lib\plugins\output\splunkstream.py", line 110, in flush
    splunkhttp.connect()
  File "C:\Program Files (x86)\Python27\lib\httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python27\lib\ssl.py", line 352, in wrap_socket
    _context=self)
  File "C:\Program Files (x86)\Python27\lib\ssl.py", line 579, in __init__
    self.do_handshake()
  File "C:\Program Files (x86)\Python27\lib\ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
**SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)**

**Comment by arctan5x** [comment]
Since this issue has been open for a while and we have released new versions 6.x.x of Eventgen, we are closing this issue. Please recreate the issue if you experience the same problem in the latest version.
