### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED - when using SplunkStream output mode

### ISSUE THREAD

**Issue by pwmcintyre** [splunk/eventgen#66]
When using outputMode = splunkstream I get SSL issues

```
root@eventgen:/eventgen# python bin/eventgen.py conf/data.conf
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/eventgen/lib/outputworker.py", line 40, in run
    self.worker.run()
  File "/eventgen/lib/outputworker.py", line 74, in run
    self.real_run()
  File "/eventgen/lib/outputworker.py", line 96, in real_run
    plugin.flush(deque(queue[:]))
  File "/eventgen/lib/plugins/output/splunkstream.py", line 110, in flush
    splunkhttp.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

I've raised a pull request which fixes the issue for me.
https://github.com/splunk/eventgen/pull/65

**Comment by lephino** [comment]
Can you let me know if this is still an issue in eventgen 6?
