### ISSUE TITLE
popleft on run

### ISSUE THREAD

**Issue by lastrecrue** [splunk/eventgen#81]
when i run sample example i have this stacktarce :
`
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/splunk_eventgen/eventgen_core.py", line 350, in _worker_do_work
    raise e
AttributeError: 'list' object has no attribute 'popleft'
`
do you have any isse ?

**Comment by lastrecrue** [comment]
i fix problem on adding 'q = deque(q)' in  eventgen/splunkstream.py on line 58.
