### ISSUE TITLE
install: both docker and using pip fail on AWS

### ISSUE THREAD

**Issue by gregcoleman398** [splunk/eventgen#84]
I know 'docker login repo.splunk.com' works anywhere I need it to, except AWS.
Is there something different needed to pull the latest, in this case eventgenx from? I am getting this on login:
**Error response from daemon: Get https://repo.splunk.com/v1/users/: dial tcp: lookup repo.splunk.com on 172.31.0.2:53: no such host**
Works fine from non-AWS systems.

I moved on to trying as a PyPI module and after splunk_eventgen installs, at exection I get the following:

root@ip-172-31-5-166:/tmp/eventgen-develop# splunk_eventgen
Traceback (most recent call last):
  File "/usr/local/bin/splunk_eventgen", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography>=1.3.4' distribution was not found and is required by requests

Reason for posting - since I can do all of this no problem on non-AWS servers, is there some networking I am missing or Ubuntu version I should have for eventgen with Splunk.

**Comment by lephino** [comment]
ping me on slack, this is an external repo which customers / public has access to, happy to answer this there :D
