### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by xrayid** [splunk/eventgen#86]
After installation evengen doesn`t work.
I see follow errors in logs.

```
2018-08-20 15:01:20 eventgen        INFO     MainProcess Logging Setup Complete.
2018-08-20 15:01:20 eventgen        INFO     MainProcess Retrieving eventgen configurations from /configs/eventgen
2018-08-20 15:01:20 eventgen        WARNING  MainProcess Could not load plugin: /opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/plugins/generator/jinja.py, skipping
2018-08-20 15:01:20 eventgen        ERROR    MainProcess No module named jinja2
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/eventgen_core.py", line 431, in _initializePlugins
    module = imp.load_module(base, mod_name, mod_path, mod_desc)
  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/plugins/generator/jinja.py", line 9, in <module>
    from jinja2 import nodes
ImportError: No module named jinja2
2018-08-20 15:01:20 eventgen        INFO     MainProcess No samples found.  Exiting.
2018-08-20 15:01:20 eventgen        INFO     MainProcess All timers started, joining queue until it's empty.
2018-08-20 15:01:20 eventgen        INFO     MainProcess All timers have finished, signalling workers to exit.
2018-08-20 15:01:20 eventgen        INFO     MainProcess All timers exited, joining generation queue until it's empty.
2018-08-20 15:01:20 eventgen        INFO     MainProcess All generators working/exited, joining output queue until it's empty.
2018-08-20 15:01:20 eventgen        INFO     MainProcess All items fully processed, stopping.
2018-08-20 15:01:20 eventgen        ERROR    MainProcess 'EventGenerator' object has no attribute 'hec_logging_handler'
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/eventgen_core.py", line 516, in join_process
    self.stop()
  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/eventgen_core.py", line 546, in stop
    self.hec_logging_handler._stopFlushTimer()
AttributeError: 'EventGenerator' object has no attribute 'hec_logging_handler'

```
Any ideas?

**Comment by richpaulson** [comment]
Hello, I'm seeing the same error -  modinput_eventgen.log.  Please let me know if there are any other logs you require.  Thanks.

2018-08-31 13:36:01,213 DEBUG [Eventgen] Initialized ModularInput Logger
2018-08-31 13:36:01,213 DEBUG [Eventgen] Setting up SA-Eventgen Modular Input
2018-08-31 13:36:04,279 DEBUG [Eventgen] Initialized ModularInput Logger
2018-08-31 13:36:04,280 DEBUG [Eventgen] Setting up SA-Eventgen Modular Input
2018-08-31 13:36:04,283 INFO [Eventgen] Initialized streaming
2018-08-31 13:36:04,283 INFO [Eventgen] Input Config is: {'server_uri': 'https://127.0.0.1:8089', 'server_host': 'master.richp.local', 'session_key': 'kr2JZQkNsQg4dXwbP93Dbr6YchTOGjdYJkospJ4_W9^RKb8FasgzgoBB^XuB_^HR^8oScBjGZ03LbaHr855l8X17zEbdK3e7zGi0PWtFV0kmtrv^b0pD7sy1hF', 'checkpoint_dir': '/opt/splunkbeta/var/lib/splunk/modinputs/modinput_eventgen', 'configuration': "{u'modinput_eventgen://default': {u'host': u'master.richp.local', u'index': u'default', u'VERBOSE': u'0', u'disabled': u'0', 'name': u'modinput_eventgen://default'}}"}
2018-08-31 13:36:04,284 INFO [Eventgen] Prepared Config
2018-08-31 13:36:04,285 INFO [Eventgen] Eventgen object generated
2018-08-31 13:36:04,286 INFO [Eventgen] Config object generated
2018-08-31 13:36:04,286 INFO [Eventgen] Config made Splunk Embedded
2018-08-31 13:36:04,408 INFO [Eventgen] Finished config parsing
2018-08-31 13:36:04,408 INFO [Eventgen] Finished parse
2018-08-31 13:36:04,418 INFO [Eventgen] Finished reload
2018-08-31 13:36:04,451 INFO [Eventgen] Finished setup pools
2018-08-31 13:36:04,453 ERROR [Eventgen] 'EventGenerator' object has no attribute 'hec_logging_handler'
Traceback (most recent call last):
  File "/opt/splunkbeta/etc/apps/SA-Eventgen/bin/modinput_eventgen.py", line 126, in run
    eventgen.start(join_after_start=True)
  File "/opt/splunkbeta/etc/apps/SA-Eventgen/lib/splunk_eventgen/eventgen_core.py", line 492, in start
    self.join_process()
  File "/opt/splunkbeta/etc/apps/SA-Eventgen/lib/splunk_eventgen/eventgen_core.py", line 519, in join_process
    raise e
AttributeError: 'EventGenerator' object has no attribute 'hec_logging_handler'
2018-08-31 13:36:04,454 INFO [Eventgen] Finished streaming

**Comment by lephino** [comment]
This looks like you're using the 7.2 beta, is that correct?

**Comment by richpaulson** [comment]
Yes, Version: 7.1.2 Beta

**Comment by arctan5x** [comment]
Error messages regarding "No module named jinja2" can be ignored since Splunk Python doesn't ship with jinja2 module. Regarding hec_logging_handler, 6.3.0 has completely removed hec_logging_handler after we merged the open source and internal versions so we would not run into that issue. Closing for now since the issue should be resolved and please reopen if you see the same issue after trying out 6.3.0.
