### ISSUE TITLE
Python errors with EventGen 6.2.1 on Splunk 7.2.1. No data being generated.

### ISSUE THREAD

**Issue by atgithub11** [splunk/eventgen#87]
Splunk Version: 7.1.2
SA-EventGen: 6.2.1 

Installed Splunk Eventgen from appstore(eventgen_621.tgz file imported directly into Splunk) and configured two simple sample data files. one is text based and another a CSV. After restarting, logs seems to indicate eventgen has recognized the files and is working but we don't see any data being generated. Also, soon after those initial logs, we get the following error being repeated multiple times.

2018-08-21 10:25:02 eventgen ERROR MainProcess string indices must be integers, not str Traceback (most recent call last): File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/eventgen_core.py", line 350, in _worker_do_work item.run() File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/generatorplugin.py", line 144, in run self.gen(count=self.count, earliest=self.start_time, latest=self.end_time, samplename=self._sample.name) File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/plugins/generator/replay.py", line 93, in gen current_event_timestamp = self._sample.getTSFromEvent(line[self._sample.timeField]) TypeError: string indices must be integers, not str 

Here are the initial logs:

2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess All timers started, joining queue until it's empty.
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Start '1' generatorWorkers for sample 'Threats.sophos'
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Creating timer object for sample 'Threats.sophos' in app 'Sample_Data'
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Start '1' generatorWorkers for sample 'isilon_auth.csv'
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Creating timer object for sample 'isilon_auth.csv' in app 'Sample_Data'
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen ERROR MainProcess No module named jinja2 Traceback (most recent call last): File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/eventgen_core.py", line 437, in _initializePlugins module = imp.load_module(base, mod_name, mod_path, mod_desc) File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/plugins/generator/jinja.py", line 9, in <module> from jinja2 import nodes ImportError: No module named jinja2
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen WARNING MainProcess Could not load plugin: /opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/plugins/generator/jinja.py, skipping
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Key 'splunkPass' in stanza 'Threats.sophos' may not be a valid setting
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Key 'splunkHost' in stanza 'Threats.sophos' may not be a valid setting
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Key 'splunkUser' in stanza 'Threats.sophos' may not be a valid setting
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Key 'splunkPass' in stanza 'isilon_auth.csv' may not be a valid setting
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Key 'splunkHost' in stanza 'isilon_auth.csv' may not be a valid setting
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Key 'splunkUser' in stanza 'isilon_auth.csv' may not be a valid setting
2018-08-21 10:21:46.251 	Splunk 	_internal 	2018-08-21 10:21:46,251 INFO [Eventgen] Finished setup pools
2018-08-21 10:21:46.238 	Splunk 	_internal 	2018-08-21 10:21:46,238 INFO [Eventgen] Finished reload
2018-08-21 10:21:46.214 	Splunk 	_internal 	2018-08-21 10:21:46,214 INFO [Eventgen] Finished parse
2018-08-21 10:21:46.214 	Splunk 	_internal 	2018-08-21 10:21:46,214 INFO [Eventgen] Finished config parsing
2018-08-21 10:21:46.155 	Splunk 	_internal 	2018-08-21 10:21:46,155 INFO [Eventgen] Config made Splunk Embedded
2018-08-21 10:21:46.155 	Splunk 	_internal 	2018-08-21 10:21:46,155 INFO [Eventgen] Config object generated
2018-08-21 10:21:46.154 	Splunk 	_internal 	2018-08-21 10:21:46,154 INFO [Eventgen] Eventgen object generated
2018-08-21 10:21:46.128 	Splunk 	_internal 	2018-08-21 10:21:46,128 INFO [Eventgen] Prepared Config
2018-08-21 10:21:46.127 	Splunk 	_internal 	2018-08-21 10:21:46,127 INFO [Eventgen] Input Config is: {'checkpoint_dir': '/opt/splunk/var/lib/splunk/modinputs/modinput_eventgen', 'configuration': "{u'modinput_eventgen://default': {u'disabled': u'0', 'name': u'modinput_eventgen://default', u'index': u'default', u'host': u'Splunk', u'VERBOSE': u'0'}}", 'session_key': 'PwZOLB95QvgdykzVRJUy9n2ogMWN3R_', 'server_uri': 'https://127.0.0.1:8089', 'server_host': 'Splunk'}
2018-08-21 10:21:46.126 	Splunk 	_internal 	2018-08-21 10:21:46,126 INFO [Eventgen] Initialized streaming
2018-08-21 10:21:46.124 	Splunk 	_internal 	2018-08-21 10:21:46,124 DEBUG [Eventgen] Setting up SA-Eventgen Modular Input
2018-08-21 10:21:46.123 	Splunk 	_internal 	2018-08-21 10:21:46,123 DEBUG [Eventgen] Initialized ModularInput Logger
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Retrieving eventgen configurations from /configs/eventgen
2018-08-21 10:21:46.000 	Splunk 	_internal 	2018-08-21 10:21:46 eventgen INFO MainProcess Logging Setup Complete.
2018-08-21 10:21:43.003 	Splunk 	_internal 	2018-08-21 10:21:43,003 DEBUG [Eventgen] Setting up SA-Eventgen Modular Input
2018-08-21 10:21:43.002 	Splunk 	_internal 	2018-08-21 10:21:43,002 DEBUG [Eventgen] Initialized ModularInput Logger 

What could be going wrong? I do see that it was unable to load jinja plugin but not sure if that is what's causing this issue. 

Any ideas?

**Comment by atgithub11** [comment]
Here are contents of /opt/splunk/etc/apps/Sample_Data/local/eventgen.conf 

 [isilon_auth.csv]
 mode = replay
 timeMultiple = 1
 backfill = -15m
 sampletype = csv
 
 outputMode = splunkstream
 index = main
 sourcetype = isilon:data
 source = syslog
 host = localhost
 splunkHost = localhost
 splunkUser = admin
 splunkPass = password
 
 token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}
 token.0.replacementType = replaytimestamp
 token.0.replacement = %Y-%m-%d %H:%M:%S
 
 
 [Threats.sophos]
 mode = replay
 timeMultiple = 1
 backfill = -15m
 sampletype = raw
 
 outputMode = splunkstream
 index = Sophos
 sourcetype = sophos:threats
 source = eventgen
 host = localhost
 splunkHost = localhost
 splunkUser = admin
 splunkPass = password
 
 token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}
 token.0.replacementType = replaytimestamp
 token.0.replacement = %Y-%m-%d %H:%M:%S

**Comment by lephino** [comment]
once you set it to sample, it generated events, but they were probably indexed at the "wrong time".  Meaning, it reparsed the timestamp that was generated (and probably wasn't replaced) and shoved them "back in time", change your time selector to all-time, and you'll probably find them.  As to the replay mode, you told it CSV, so it's looking for a _time field by default to be in the csv.  Simply set your timefield to _raw and I think you'll fix replay mode.

**Comment by atgithub11** [comment]
Thanks for the suggestion. It is working properly now.
