### ISSUE TITLE
Eventgen not generating any events

### ISSUE THREAD

**Issue by lakshman237** [splunk/eventgen#88]
I use eventgen on a regular basis for windows, firewalls and other network devices and they all work fine.
I have taken the latest version 6.2.1 from gitHub and used the packaging approach as per the documentation [ for generating eventgen*.spl] and installed successfully. I have ensured the app is global, modinput enabled and no errors in 'modinput_eventgen.log' or eventgen-main.log. I am on splunk 7.0.4 and restarted it a few times.

However, I still don't see new events getting generated and no error messages in the logs. In the older versions , we can invoke 'python $SPLUNK_HOME/SA-Eventgen/bin/eventgen.py -v -s <samplefle>  path-to-local/eventgen.conf to reply the events on screen/file and look at errors.  How do go about troubleshooting the new versions?  Any help is appreciated.

Also seeing the following errors:

2018-10-08 14:59:05 eventgen        ERROR    MainProcess Exception <type 'exceptions.IOError'> happened.

Traceback (most recent call last):

  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/plugins/generator/default.py", line 108, in gen

    self._out.bulksend(l)

  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/eventgenoutput.py", line 77, in bulksend

    self.flush()

  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/eventgenoutput.py", line 126, in flush

    outputer.run()

  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/outputplugin.py", line 51, in run

    self.flush(q=self.events)

  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/plugins/output/modinput.py", line 42, in flush

    print out

IOError: [Errno 32] Broken pipe

2018-10-08 14:59:06 eventgen        ERROR    MainProcess [Errno 32] Broken pipe

Traceback (most recent call last):

  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/eventgen_core.py", line 344, in _worker_do_work

    item.run()

  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/generatorplugin.py", line 144, in run

    self.gen(count=self.count, earliest=self.start_time, latest=self.end_time, samplename=self._sample.name)

  File "/opt/splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/lib/plugins/generator/default.py", line 112, in gen

    raise e

IOError: [Errno 32] Broken pipe

**Comment by arctan5x** [comment]
To debug, would you post your eventgen.conf and sample files you are using?

**Comment by arctan5x** [comment]
Please reopen if your issue persists. Closing this since it has been a while from the last update.
