### ISSUE TITLE
pyOpenSSL is missing from setup.py's install_requires

### ISSUE THREAD

**Issue by qn7o** [splunk/eventgen#96]
Tested using conda on the latest master and develop.  Installing the package manually solves the issue.

# Installation
```
$ conda create -n eg ujson
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /opt/miniconda2/envs/eg:

The following NEW packages will be INSTALLED:

    ca-certificates: 2018.03.07-0           
    certifi:         2018.10.15-py27_0      
    libedit:         3.1.20170329-h6b74fdf_2
    libffi:          3.2.1-hd88cf55_4       
    libgcc-ng:       8.2.0-hdf63c60_1       
    libstdcxx-ng:    8.2.0-hdf63c60_1       
    ncurses:         6.1-hf484d3e_0         
    openssl:         1.1.1-h7b6447c_0       
    pip:             18.1-py27_0            
    python:          2.7.15-h9bab390_2      
    readline:        7.0-h7b6447c_5         
    setuptools:      40.5.0-py27_0          
    sqlite:          3.25.2-h7b6447c_0      
    tk:              8.6.8-hbc83047_0       
    ujson:           1.35-py27h14c3975_0    
    wheel:           0.32.2-py27_0          
    zlib:            1.2.11-ha838bed_2      

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate eg
#
# To deactivate an active environment, use:
# > source deactivate
#

$ source activate eg
$ git br
  develop
* master

$ git top
758c6d6 (2018-11-01 14:57:03 -0600) Set theme jekyll-theme-slate (HEAD, origin/master, master) <Brian Bingham>
467f2e1 (2018-11-01 14:56:47 -0600) Set theme jekyll-theme-time-machine <Brian Bingham>
3b2a721 (2018-11-01 14:56:18 -0600) Set theme jekyll-theme-slate <Brian Bingham>
24e424f (2018-10-26 16:10:34 -0700) Rename INDEX.md to index.md <Tony Lee>
9d8c3ca (2018-10-26 16:00:38 -0700) Release 6.3.0 (tag: 6.3.0) <tonyl>

$ pip install -e .
[...]
```

# Calling eventgen
```
$ splunk_eventgen -v generate /path/to/eventgen.conf 
Traceback (most recent call last):
  File "/opt/miniconda2/envs/eg/bin/splunk_eventgen", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/miniconda2/envs/eg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3123, in <module>
    @_call_aside
  File "/opt/miniconda2/envs/eg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3107, in _call_aside
    f(*args, **kwargs)
  File "/opt/miniconda2/envs/eg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3136, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/miniconda2/envs/eg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/opt/miniconda2/envs/eg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/miniconda2/envs/eg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyOpenSSL>=0.14; extra == "security"' distribution was not found and is required by requests
```

# Fixing the issue, and calling eventgen again
```
$ pip install pyOpenSSL
[...]

$ splunk_eventgen -v generate /path/to/eventgen.conf 
2018-11-06 17:50:15 eventgen        INFO     MainProcess Logging Setup Complete.
2018-11-06 17:50:15 eventgen        DEBUG    MainProcess Parsing configuration files.
2018-11-06 17:50:15 eventgen        INFO     MainProcess Retrieving eventgen configurations with ConfigParser()
```

**Comment by arctan5x** [comment]
PR made to address this issue (https://github.com/splunk/eventgen/pull/97).
